# Generated by Django 4.2.3 on 2023-11-02 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('classification', models.CharField(max_length=200)),
                ('intention', models.TextField(max_length=200)),
                ('implications', models.TextField(max_length=200)),
                ('dose', models.CharField(max_length=200)),
                ('route', models.CharField(max_length=200)),
                ('frequency', models.CharField(max_length=200)),
            ],
        ),
    ]
