# Generated by Django 4.2.3 on 2023-11-17 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_medication_implications_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medication',
            options={'ordering': ['-name']},
        ),
    ]
