# Generated by Django 4.2.9 on 2025-05-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_medication_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='frequency',
            field=models.CharField(choices=[('QD', 'Once Daily'), ('BID', 'Twice Daily'), ('TID', 'Three Times Daily'), ('QID', 'Four Times Daily'), ('PRN', 'As Needed')], default='QD', max_length=3),
        ),
    ]
